version: "3"
services:
  postgres:
    container_name: 1Filter
    image: postgres:latest
    ports:
      - "5436:5436"
    volumes:
      - /date/postgres:/date/postgres
    env_file:
      - docker.env
    command:
      -p 5436
    networks:
      - postgres

  postgres_tests:
      container_name: Filter_test
      image: postgres:latest
      volumes:
        - /date/postgres:/date/postgres
      env_file:
        - docker_test.env
      ports:
        - "5437:5437"
      command:
        -p 5437
      networks:
        - postgres


  pgadmin:
    links:
      - postgres:1Filter
      - postgres:1Filter_test
    container_name: pgadmin1filter_
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /date/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
      - .env
    networks:
      - postgres


networks:
  postgres:
    driver: bridge
